sudo: required
services:
  - docker

before_install:
  - docker build -t jameelvm1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jameelvm1/react-test npm test -- --coverage

after_success:
  - docker build -t jameelvm1/multi-client ./client
  - docker build -t jameelvm1/multi-nginx ./nginx
  - docker build -t jameelvm1/multi-server ./server
  - docker build -t jameelvm1/multi-worker ./worker

#Login in to Docker CLI

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


# Take those images and pushes to Docker Hub
- docker push jameelvm1/multi-client
- docker push jameelvm1/multi-nginx
- docker push jameelvm1/multi-server
- docker push jameelvm1/multi-worker