sudo: required
services:
  - docker

before_install:
  - docker build -t jameelvm1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jameelvm1/react-test npm test -- --coverage

after_success:
  - docker build -t jameelvm1/multi-client ./client
  - docker build -t jameelvm1/multi-nginx ./nginx
  - docker build -t jameelvm1/multi-server ./server
  - docker build -t jameelvm1/multi-worker ./worker

